"use client";

import { useMemo, useState } from "react";
import { Check, Copy, Download } from "lucide-react";
import type { DeploymentConfig } from "@boundless-stock/shared";
import type { LaunchPresets } from "@/lib/presets";
import { Badge, Card, CardHeader, VmBadge, cx } from "@/components/ui";

const STEPS = ["Asset", "Backing", "Distribution", "Compliance", "Market", "Review"] as const;
const SHARED_DECIMALS = 6;

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="text-sm font-medium">{label}</span>
      <div className="mt-1.5">{children}</div>
      {hint && <span className="mt-1 block text-xs text-muted">{hint}</span>}
    </label>
  );
}

const inputCls =
  "w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent-soft";

export function LaunchWizard({ presets }: { presets: LaunchPresets }) {
  const [step, setStep] = useState(0);
  const env = "local" as "local" | "testnet";
  const [asset, setAsset] = useState({ name: "Tokenized Apple Inc.", symbol: "tAAPL", decimals: 18, supply: "1000000", existing: "" });
  const [mirrorKeys, setMirrorKeys] = useState<string[]>([]);
  const [backing, setBacking] = useState({ shares: "1000000", source: "custodian attestation", asOf: new Date().toISOString().slice(0, 10) });
  const [gate, setGate] = useState(true);
  const [partners, setPartners] = useState([{ name: "", maxFeeBps: 50, signer: "" }]);
  const [market, setMarket] = useState({
    feeTier: presets.pool.feeTier,
    initialPrice: presets.pool.initialPrice,
    baseLiquidity: presets.pool.baseLiquidity,
    quoteLiquidity: presets.pool.quoteLiquidity,
  });
  const [copied, setCopied] = useState(false);

  const chains = presets.chains.filter((c) => c.environment === env);
  // Solana is home: the asset is issued there and its market lives there.
  const home = chains.find((c) => c.vm === "svm");
  const homeKey = home?.key ?? "";
  const mirrors = chains.filter((c) => mirrorKeys.includes(c.key) && c.key !== homeKey);

  const problems: string[] = [];
  if (!asset.symbol.trim()) problems.push("The asset needs a symbol.");
  if (asset.decimals < SHARED_DECIMALS) problems.push(`Decimals must be at least ${SHARED_DECIMALS}, the precision amounts cross chains in.`);
  if (!home) problems.push("No Solana chain is available in this chain set.");
  if (mirrors.length === 0) problems.push("Choose at least one distribution chain.");
  if (Number(backing.shares) * 1 < Number(asset.supply) && !asset.existing) problems.push("The shares held back fewer tokens than you plan to issue.");

  const config = useMemo(() => {
    if (!home) return undefined;
    const c: DeploymentConfig & { _comment: string } = {
      name: `boundless-${asset.symbol.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-") || "asset"}`,
      _comment: "Generated by the Boundless Stock launch wizard. Review, then: boundless-stock deploy --config <this file>",
      token: {
        name: asset.name,
        symbol: asset.symbol.trim(),
        decimals: asset.decimals,
        initialSupply: asset.supply,
        ...(asset.existing.trim() ? { existingToken: asset.existing.trim() } : {}),
        reserves: { shares: backing.shares, source: backing.source, asOf: backing.asOf },
      },
      quoteAsset: { name: "USD Coin", symbol: "USDC", decimals: 6, initialSupply: "50000000" },
      homeChain: home.config,
      mirrorChains: mirrors.map((m) => m.config),
      pool: { ...presets.pool, ...market },
      relay: presets.relay,
      partners: {
        required: gate,
        partners: partners
          .filter((p) => p.name.trim() && p.signer.trim())
          .map((p, i) => ({ id: i + 1, name: p.name.trim(), maxFeeBps: p.maxFeeBps, evm: { signer: p.signer.trim(), feeRecipient: p.signer.trim() } })),
      },
    };
    return c;
  }, [asset, home, mirrors, market, presets, backing, gate, partners]);
  const json = config ? JSON.stringify(config, null, 2) : "";

  const next = () => setStep((s) => Math.min(s + 1, STEPS.length - 1));
  const back = () => setStep((s) => Math.max(s - 1, 0));

  return (
    <div className="grid gap-8 lg:grid-cols-[200px_1fr]">
      <ol className="flex gap-2 overflow-x-auto lg:flex-col">
        {STEPS.map((s, i) => (
          <li key={s}>
            <button
              type="button"
              onClick={() => setStep(i)}
              className={cx(
                "flex w-full items-center gap-3 whitespace-nowrap rounded-lg px-3 py-2 text-left text-sm",
                i === step ? "bg-surface font-medium shadow-sm ring-1 ring-line" : "text-muted hover:text-fg"
              )}
            >
              <span
                className={cx(
                  "grid h-6 w-6 place-items-center rounded-full text-xs",
                  i < step ? "bg-accent text-accent-contrast" : i === step ? "bg-accent-soft text-accent" : "bg-surface-2"
                )}
              >
                {i < step ? <Check size={12} aria-hidden /> : i + 1}
              </span>
              {s}
            </button>
          </li>
        ))}
      </ol>

      <Card>
        <CardHeader title={STEPS[step]} />
        <div className="space-y-5 p-5">
          {step === 0 && (
            <>
              <div className="grid gap-4 sm:grid-cols-2">
                <Field label="Name">
                  <input className={inputCls} value={asset.name} onChange={(e) => setAsset({ ...asset, name: e.target.value })} />
                </Field>
                <Field label="Symbol">
                  <input className={inputCls} value={asset.symbol} onChange={(e) => setAsset({ ...asset, symbol: e.target.value })} />
                </Field>
                <Field label="Decimals" hint="On the home chain. Each chain may use its own; amounts cross in 6 shared decimals.">
                  <input type="number" min={6} max={18} className={inputCls} value={asset.decimals}
                    onChange={(e) => setAsset({ ...asset, decimals: Number(e.target.value) })} />
                </Field>
                <Field label="Supply to issue" hint="Issued once, on Solana, and never more. Ignored when adapting an existing token.">
                  <input className={inputCls} value={asset.supply} onChange={(e) => setAsset({ ...asset, supply: e.target.value })} />
                </Field>
              </div>
              <Field
                label="Existing token (optional)"
                hint="Already issued on Solana? Its SPL mint. It is adapted, not replaced: holders keep their balances and you keep the mint authority."
              >
                <input className={inputCls} placeholder="A Solana mint address" value={asset.existing}
                  onChange={(e) => setAsset({ ...asset, existing: e.target.value })} />
              </Field>
            </>
          )}

          {step === 1 && (
            <>
              <p className="text-sm text-muted">
                What backs the asset. Its supply on every chain is checked against this continuously, and shown as proof of reserves.
              </p>
              <div className="grid gap-4 sm:grid-cols-3">
                <Field label="Shares held" hint="Held by the custodian for this asset.">
                  <input className={inputCls} value={backing.shares} onChange={(e) => setBacking({ ...backing, shares: e.target.value })} />
                </Field>
                <Field label="Reported by" hint="Custodian, transfer agent, or an oracle feed.">
                  <input className={inputCls} value={backing.source} onChange={(e) => setBacking({ ...backing, source: e.target.value })} />
                </Field>
                <Field label="As of">
                  <input type="date" className={inputCls} value={backing.asOf} onChange={(e) => setBacking({ ...backing, asOf: e.target.value })} />
                </Field>
              </div>
              <div className="rounded-lg bg-surface-2 p-4 text-sm">
                {Number(backing.shares).toLocaleString()} shares back {Number(backing.shares).toLocaleString()} {asset.symbol || "tokens"}.{" "}
                {Number(backing.shares) >= Number(asset.supply) ? (
                  <span className="text-ok">Enough to issue {Number(asset.supply).toLocaleString()}.</span>
                ) : (
                  <span className="text-bad">Not enough to issue {Number(asset.supply).toLocaleString()}.</span>
                )}
              </div>
            </>
          )}

          {step === 2 && (
            <>
              <p className="text-sm text-muted">
                The chains to distribute to. Each gets a mirror of the asset, minted only when stock arrives from Solana, and no
                market it needs to fund: orders placed through Boundless Stock fill on the Solana market, and holders can still transfer and trade the mirror locally.
              </p>
              <div className="grid gap-3 sm:grid-cols-2">
                {chains.filter((c) => c.key !== homeKey).map((c) => {
                  const on = mirrorKeys.includes(c.key);
                  return (
                    <button key={c.key} type="button"
                      onClick={() => setMirrorKeys((m) => (on ? m.filter((k) => k !== c.key) : [...m, c.key]))}
                      className={cx("flex items-center justify-between gap-2 rounded-lg border p-4 text-left", on ? "border-accent ring-2 ring-accent-soft" : "border-line hover:bg-surface-2")}>
                      <span>
                        <span className="font-medium">{c.name}</span>
                        <span className="block text-xs text-muted">{c.vm === "svm" ? "SVM chain" : "EVM chain"}</span>
                      </span>
                      <span className="flex items-center gap-2">
                        <VmBadge vm={c.vm} />
                        <span className={cx("grid h-5 w-5 place-items-center rounded border", on ? "border-accent bg-accent text-accent-contrast" : "border-line")}>
                          {on && <Check size={12} aria-hidden />}
                        </span>
                      </span>
                    </button>
                  );
                })}
              </div>
            </>
          )}

          {step === 3 && (
            <>
              <label className="flex items-start gap-3 rounded-lg border border-line p-4">
                <input type="checkbox" className="mt-1" checked={gate} onChange={(e) => setGate(e.target.checked)} />
                <span>
                  <span className="text-sm font-medium">Partner-approved orders only</span>
                  <span className="block text-sm text-muted">
                    Only orders approved by a registered partner reach the market. Each partner runs KYC on its own users.
                  </span>
                </span>
              </label>
              <div className="space-y-3">
                <div className="text-sm font-medium">Distribution partners</div>
                {partners.map((p, i) => (
                  <div key={i} className="grid gap-3 sm:grid-cols-[1fr_140px_1.4fr]">
                    <input className={inputCls} placeholder="Partner name" value={p.name}
                      onChange={(e) => setPartners(partners.map((x, j) => (j === i ? { ...x, name: e.target.value } : x)))} />
                    <input type="number" min={0} max={300} className={inputCls} value={p.maxFeeBps} aria-label="Fee ceiling in basis points"
                      onChange={(e) => setPartners(partners.map((x, j) => (j === i ? { ...x, maxFeeBps: Number(e.target.value) } : x)))} />
                    <input className={inputCls} placeholder="Approval key (0x…)" value={p.signer}
                      onChange={(e) => setPartners(partners.map((x, j) => (j === i ? { ...x, signer: e.target.value } : x)))} />
                  </div>
                ))}
                <button type="button" onClick={() => setPartners([...partners, { name: "", maxFeeBps: 50, signer: "" }])}
                  className="rounded-lg border border-line px-3 py-1.5 text-sm hover:bg-surface-2">Add a partner</button>
                <p className="text-xs text-muted">Fee ceiling in basis points (50 = 0.50%). Fees are escrowed and paid only when an order fills.</p>
              </div>
            </>
          )}

          {step === 4 && (
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Opening price" hint="USDC per unit of the asset, on the Solana market.">
                <input className={inputCls} value={market.initialPrice} onChange={(e) => setMarket({ ...market, initialPrice: e.target.value })} />
              </Field>
              <Field label="Trading fee">
                <select className={inputCls} value={market.feeTier} onChange={(e) => setMarket({ ...market, feeTier: Number(e.target.value) })}>
                  {[500, 3000, 10000].map((f) => <option key={f} value={f}>{f / 10_000}%</option>)}
                </select>
              </Field>
              <Field label={`Seed liquidity — ${asset.symbol || "asset"}`}>
                <input className={inputCls} value={market.baseLiquidity} onChange={(e) => setMarket({ ...market, baseLiquidity: e.target.value })} />
              </Field>
              <Field label="Seed liquidity — USDC">
                <input className={inputCls} value={market.quoteLiquidity} onChange={(e) => setMarket({ ...market, quoteLiquidity: e.target.value })} />
              </Field>
            </div>
          )}

          {step === 5 && (
            <>
              {problems.length > 0 ? (
                <ul className="space-y-1 rounded-lg bg-bad-soft p-4 text-sm text-bad">
                  {problems.map((p) => <li key={p}>{p}</li>)}
                </ul>
              ) : (
                <div className="flex flex-wrap items-center gap-2 text-sm">
                  <Badge tone="accent">{asset.existing ? "Adapt" : "Launch"}</Badge>
                  {asset.symbol} issued on <strong>{home?.name}</strong>, backed by {Number(backing.shares).toLocaleString()} shares, distributed to{" "}
                  {mirrors.map((m) => m.name).join(", ")}{gate ? ", partner-approved orders only" : ""}.
                </div>
              )}
              {config && (
                <div className="relative">
                  <div className="absolute right-2 top-2 flex gap-1">
                    <button type="button" aria-label="Copy config"
                      onClick={() => { navigator.clipboard.writeText(json); setCopied(true); setTimeout(() => setCopied(false), 1500); }}
                      className="rounded-md border border-line bg-surface p-1.5 text-muted hover:text-fg">
                      {copied ? <Check size={14} aria-hidden /> : <Copy size={14} aria-hidden />}
                    </button>
                    <button type="button" aria-label="Download config"
                      onClick={() => {
                        const url = URL.createObjectURL(new Blob([json + "\n"], { type: "application/json" }));
                        const a = document.createElement("a");
                        a.href = url;
                        a.download = `${config.name}.json`;
                        a.click();
                        URL.revokeObjectURL(url);
                      }}
                      className="rounded-md border border-line bg-surface p-1.5 text-muted hover:text-fg">
                      <Download size={14} aria-hidden />
                    </button>
                  </div>
                  <pre className="max-h-96 overflow-auto rounded-lg bg-surface-2 p-4 font-mono text-xs leading-relaxed">{json}</pre>
                </div>
              )}
              <div className="rounded-lg border border-line p-4 text-sm">
                Save this as <code className="font-mono">config/{config?.name ?? "asset"}.json</code>, then deploy it:
                <pre className="mt-2 overflow-x-auto rounded-md bg-surface-2 p-3 font-mono text-xs">boundless-stock deploy --config config/{config?.name ?? "asset"}.json</pre>
              </div>
            </>
          )}

          <div className="flex justify-between border-t border-line pt-5">
            <button type="button" onClick={back} disabled={step === 0}
              className="rounded-lg border border-line px-4 py-2 text-sm disabled:opacity-40">Back</button>
            {step < STEPS.length - 1 && (
              <button type="button" onClick={next}
                disabled={step === 2 && mirrors.length === 0}
                className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-accent-contrast disabled:opacity-40">
                Continue
              </button>
            )}
          </div>
        </div>
      </Card>
    </div>
  );
}
