"use client";

import { useMemo, useState } from "react";
import { Check, Copy, Download } from "lucide-react";
import type { DeploymentConfig } from "@boundless-stock/shared";
import type { LaunchPresets } from "@/lib/presets";
import { Badge, Card, CardHeader, PreviewNote, VmBadge, cx } from "@/components/ui";

const STEPS = ["Asset", "Home chain", "Mirrors", "Market", "Review"] as const;
const SHARED_DECIMALS = 6;

function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="text-sm font-medium">{label}</span>
      <div className="mt-1.5">{children}</div>
      {hint && <span className="mt-1 block text-xs text-muted">{hint}</span>}
    </label>
  );
}

const inputCls =
  "w-full rounded-lg border border-line bg-surface px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent-soft";

export function LaunchWizard({ presets }: { presets: LaunchPresets }) {
  const [step, setStep] = useState(0);
  const [env, setEnv] = useState<"local" | "testnet">("local");
  const [asset, setAsset] = useState({ name: "Tokenized Apple Inc.", symbol: "tAAPL", decimals: 18, supply: "1000000", existing: "" });
  const [homeKey, setHomeKey] = useState<string>("");
  const [mirrorKeys, setMirrorKeys] = useState<string[]>([]);
  const [market, setMarket] = useState({
    feeTier: presets.pool.feeTier,
    initialPrice: presets.pool.initialPrice,
    baseLiquidity: presets.pool.baseLiquidity,
    quoteLiquidity: presets.pool.quoteLiquidity,
  });
  const [copied, setCopied] = useState(false);

  const chains = presets.chains.filter((c) => c.environment === env);
  const home = chains.find((c) => c.key === homeKey);
  const mirrors = chains.filter((c) => mirrorKeys.includes(c.key) && c.key !== homeKey);

  const problems: string[] = [];
  if (!asset.symbol.trim()) problems.push("The asset needs a symbol.");
  if (asset.decimals < SHARED_DECIMALS) problems.push(`Decimals must be at least ${SHARED_DECIMALS}, the precision amounts cross chains in.`);
  if (!home) problems.push("Choose a home chain.");
  if (mirrors.length === 0) problems.push("Choose at least one mirror chain.");

  const config = useMemo(() => {
    if (!home) return undefined;
    const c: DeploymentConfig & { _comment: string } = {
      name: `crossstock-${asset.symbol.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-") || "asset"}`,
      _comment: "Generated by the Boundless Stock launch wizard. Review, then: npm run deploy -- --config <this file>",
      token: {
        name: asset.name,
        symbol: asset.symbol.trim(),
        decimals: asset.decimals,
        initialSupply: asset.supply,
        ...(asset.existing.trim() ? { existingToken: asset.existing.trim() } : {}),
      },
      quoteAsset: { name: "USD Coin", symbol: "USDC", decimals: 6, initialSupply: "50000000" },
      homeChain: home.config,
      mirrorChains: mirrors.map((m) => m.config),
      pool: { ...presets.pool, ...market },
      relay: presets.relay,
    };
    return c;
  }, [asset, home, mirrors, market, presets]);
  const json = config ? JSON.stringify(config, null, 2) : "";

  const next = () => setStep((s) => Math.min(s + 1, STEPS.length - 1));
  const back = () => setStep((s) => Math.max(s - 1, 0));

  return (
    <div className="grid gap-8 lg:grid-cols-[200px_1fr]">
      <ol className="flex gap-2 overflow-x-auto lg:flex-col">
        {STEPS.map((s, i) => (
          <li key={s}>
            <button
              type="button"
              onClick={() => setStep(i)}
              className={cx(
                "flex w-full items-center gap-3 whitespace-nowrap rounded-lg px-3 py-2 text-left text-sm",
                i === step ? "bg-surface font-medium shadow-sm ring-1 ring-line" : "text-muted hover:text-fg"
              )}
            >
              <span
                className={cx(
                  "grid h-6 w-6 place-items-center rounded-full text-xs",
                  i < step ? "bg-accent text-accent-contrast" : i === step ? "bg-accent-soft text-accent" : "bg-surface-2"
                )}
              >
                {i < step ? <Check size={12} aria-hidden /> : i + 1}
              </span>
              {s}
            </button>
          </li>
        ))}
      </ol>

      <Card>
        <CardHeader title={STEPS[step]} />
        <div className="space-y-5 p-5">
          {step === 0 && (
            <>
              <div className="grid gap-4 sm:grid-cols-2">
                <Field label="Name">
                  <input className={inputCls} value={asset.name} onChange={(e) => setAsset({ ...asset, name: e.target.value })} />
                </Field>
                <Field label="Symbol">
                  <input className={inputCls} value={asset.symbol} onChange={(e) => setAsset({ ...asset, symbol: e.target.value })} />
                </Field>
                <Field label="Decimals" hint="On the home chain. Each chain may use its own; amounts cross in 6 shared decimals.">
                  <input type="number" min={6} max={18} className={inputCls} value={asset.decimals}
                    onChange={(e) => setAsset({ ...asset, decimals: Number(e.target.value) })} />
                </Field>
                <Field label="Genesis supply" hint="Minted once, on the home chain. Ignored when adapting an existing token.">
                  <input className={inputCls} value={asset.supply} onChange={(e) => setAsset({ ...asset, supply: e.target.value })} />
                </Field>
              </div>
              <Field
                label="Existing token (optional)"
                hint="Already issued on the home chain? Its address (or SPL mint). It will be adapted — locked behind an adapter — not replaced."
              >
                <input className={inputCls} placeholder="0x… or a Solana mint address" value={asset.existing}
                  onChange={(e) => setAsset({ ...asset, existing: e.target.value })} />
              </Field>
            </>
          )}

          {step === 1 && (
            <>
              <div className="inline-flex rounded-lg border border-line p-0.5 text-sm">
                {(["local", "testnet"] as const).map((e) => (
                  <button key={e} type="button"
                    onClick={() => { setEnv(e); setHomeKey(""); setMirrorKeys([]); }}
                    className={cx("rounded-md px-3 py-1.5", env === e ? "bg-surface-2 font-medium" : "text-muted")}>
                    {e === "local" ? "Local chain set" : "Testnets"}
                  </button>
                ))}
              </div>
              <p className="text-sm text-muted">The home chain holds the full supply and the only market. Any chain can be home — EVM or Solana.</p>
              <div className="grid gap-3 sm:grid-cols-2">
                {chains.map((c) => (
                  <button key={c.key} type="button" onClick={() => { setHomeKey(c.key); setMirrorKeys((m) => m.filter((k) => k !== c.key)); }}
                    className={cx("rounded-lg border p-4 text-left", homeKey === c.key ? "border-accent ring-2 ring-accent-soft" : "border-line hover:bg-surface-2")}>
                    <div className="flex items-center justify-between gap-2">
                      <span className="font-medium">{c.name}</span>
                      <VmBadge vm={c.vm} />
                    </div>
                    <div className="mt-1 text-xs text-muted">
                      eid {c.eid} · market on {c.vm === "svm" ? "Orca Whirlpool" : "Uniswap V3"}
                    </div>
                  </button>
                ))}
              </div>
            </>
          )}

          {step === 2 && (
            <>
              <p className="text-sm text-muted">Mirrors hold no market. Users there buy and sell against the home market in one transaction.</p>
              <div className="grid gap-3 sm:grid-cols-2">
                {chains.filter((c) => c.key !== homeKey).map((c) => {
                  const on = mirrorKeys.includes(c.key);
                  return (
                    <button key={c.key} type="button"
                      onClick={() => setMirrorKeys((m) => (on ? m.filter((k) => k !== c.key) : [...m, c.key]))}
                      className={cx("flex items-center justify-between gap-2 rounded-lg border p-4 text-left", on ? "border-accent ring-2 ring-accent-soft" : "border-line hover:bg-surface-2")}>
                      <span>
                        <span className="font-medium">{c.name}</span>
                        <span className="block text-xs text-muted">eid {c.eid}</span>
                      </span>
                      <span className="flex items-center gap-2">
                        <VmBadge vm={c.vm} />
                        <span className={cx("grid h-5 w-5 place-items-center rounded border", on ? "border-accent bg-accent text-accent-contrast" : "border-line")}>
                          {on && <Check size={12} aria-hidden />}
                        </span>
                      </span>
                    </button>
                  );
                })}
              </div>
            </>
          )}

          {step === 3 && (
            <div className="grid gap-4 sm:grid-cols-2">
              <Field label="Initial price" hint="Quote per unit of the asset.">
                <input className={inputCls} value={market.initialPrice} onChange={(e) => setMarket({ ...market, initialPrice: e.target.value })} />
              </Field>
              <Field label="Fee tier" hint="In hundredths of a basis point: 3000 = 0.30%.">
                <select className={inputCls} value={market.feeTier} onChange={(e) => setMarket({ ...market, feeTier: Number(e.target.value) })}>
                  {[500, 3000, 10000].map((f) => <option key={f} value={f}>{f / 10_000}%</option>)}
                </select>
              </Field>
              <Field label={`Seed liquidity — ${asset.symbol || "asset"}`}>
                <input className={inputCls} value={market.baseLiquidity} onChange={(e) => setMarket({ ...market, baseLiquidity: e.target.value })} />
              </Field>
              <Field label="Seed liquidity — USDC">
                <input className={inputCls} value={market.quoteLiquidity} onChange={(e) => setMarket({ ...market, quoteLiquidity: e.target.value })} />
              </Field>
            </div>
          )}

          {step === 4 && (
            <>
              {problems.length > 0 ? (
                <ul className="space-y-1 rounded-lg bg-bad-soft p-4 text-sm text-bad">
                  {problems.map((p) => <li key={p}>{p}</li>)}
                </ul>
              ) : (
                <div className="flex flex-wrap items-center gap-2 text-sm">
                  <Badge tone="accent">{asset.existing ? "Adapt" : "Launch"}</Badge>
                  {asset.symbol} on <strong>{home?.name}</strong>, mirrored to {mirrors.map((m) => m.name).join(", ")}.
                </div>
              )}
              {config && (
                <div className="relative">
                  <div className="absolute right-2 top-2 flex gap-1">
                    <button type="button" aria-label="Copy config"
                      onClick={() => { navigator.clipboard.writeText(json); setCopied(true); setTimeout(() => setCopied(false), 1500); }}
                      className="rounded-md border border-line bg-surface p-1.5 text-muted hover:text-fg">
                      {copied ? <Check size={14} aria-hidden /> : <Copy size={14} aria-hidden />}
                    </button>
                    <button type="button" aria-label="Download config"
                      onClick={() => {
                        const url = URL.createObjectURL(new Blob([json + "\n"], { type: "application/json" }));
                        const a = document.createElement("a");
                        a.href = url;
                        a.download = `${config.name}.json`;
                        a.click();
                        URL.revokeObjectURL(url);
                      }}
                      className="rounded-md border border-line bg-surface p-1.5 text-muted hover:text-fg">
                      <Download size={14} aria-hidden />
                    </button>
                  </div>
                  <pre className="max-h-96 overflow-auto rounded-lg bg-surface-2 p-4 font-mono text-xs leading-relaxed">{json}</pre>
                </div>
              )}
              <PreviewNote>
                Deploying from the browser comes with the deploy service (phase 3). Today, save this as
                <code className="mx-1 font-mono">config/{config?.name.replace(/^crossstock-/, "") ?? "asset"}.json</code>
                and run <code className="font-mono">npm run deploy -- --config</code> with it.
              </PreviewNote>
            </>
          )}

          <div className="flex justify-between border-t border-line pt-5">
            <button type="button" onClick={back} disabled={step === 0}
              className="rounded-lg border border-line px-4 py-2 text-sm disabled:opacity-40">Back</button>
            {step < STEPS.length - 1 && (
              <button type="button" onClick={next}
                disabled={(step === 1 && !home) || (step === 2 && mirrors.length === 0)}
                className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-accent-contrast disabled:opacity-40">
                Continue
              </button>
            )}
          </div>
        </div>
      </Card>
    </div>
  );
}
